version: "3.7"
volumes:
  postgres-data:

services:

  database:
    image: postgres:11-alpine
    restart: always
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "pass"

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8280:8080"
    environment:
      ADMINER_DEFAULT_SERVER: database
      ADMINER_DESIGN: lucas-sandery
